# Generated by Django 5.0.7 on 2024-07-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('employee_id', models.IntegerField(max_length=9)),
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_start_date_time', models.DateTimeField(null=True)),
                ('shift_end_date_time', models.DateTimeField(null=True)),
                ('type_of_shift', models.CharField(max_length=100, null=True)),
                ('length_of_the_shift', models.FloatField(null=True)),
                ('client', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('amount_of_km', models.FloatField(blank=True, default=0, max_length=30, null=True)),
                ('public_transport', models.FloatField(blank=True, default=0, max_length=30, null=True)),
                ('food', models.FloatField(blank=True, default=0, max_length=30, null=True)),
                ('shift_pay', models.FloatField(default=0, max_length=30, null=True)),
                ('parking_refund', models.FloatField(blank=True, default=0, max_length=30, null=True)),
                ('parking_receipt', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TempShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
