# Generated by Django 5.0.7 on 2024-07-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='parking_receipt',
        ),
    ]
