# Generated by Django 5.0.7 on 2024-07-25 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_remove_shift_parking_receipt'),
        ('site_base', '0002_remove_workschedule_name_of_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='work_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='site_base.workschedule'),
        ),
    ]
