# Generated by Django 5.0.7 on 2024-07-31 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_shift_work_schedule'),
        ('site_base', '0003_updatemessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='site_base.workschedule'),
        ),
    ]
