# Generated by Django 5.0.7 on 2024-07-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_alter_shift_work_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='employee_id',
            field=models.IntegerField(),
        ),
    ]
