# Generated by Django 5.0.7 on 2024-07-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=30)),
                ('client', models.CharField(max_length=30)),
                ('type_of_shift', models.CharField(max_length=100, null=True)),
                ('beginning_time', models.CharField(max_length=30)),
                ('num_of_employees', models.CharField(max_length=30)),
                ('name_of_employees', models.TextField(null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
