# Generated by Django 5.0.7 on 2024-07-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesWaitingForApproval',
            fields=[
                ('user_name', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('cell_phone', models.CharField(max_length=30, null=True)),
                ('pass1', models.CharField(max_length=30, null=True)),
                ('pass2', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
